### ISSUE TITLE
Where are the GCC toolchain builds?

### ISSUE THREAD

**Issue by aswild** [MarvellEmbeddedProcessors/Octeon-Toolchain#2]
It appears that this repo is the new home of https://github.com/Cavium-Open-Source-Distributions/OCTEON-SDK (which no longer exists), but the precompiled toolchains - e.g. OCTEON-SDK-5.1-tools, haven't been copied over.

Are there plans for Marvell to re-upload Cavium's binary toolchain builds?

**Comment by jiam-marvell** [comment]
This repo is only for toolchain source code. No binary here.
All binaries need to consult Sales/Marketing

**Comment by aswild** [comment]
Corporate takeover link rot strikes again!

Thanks for the answer, Derek.
